services:
  site:
    container_name: site
    restart: unless-stopped
    image: php:8-fpm
    volumes:
      - $PWD/site:/var/www/html
      - $PWD/fpm/site.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - php_socket:/run/php
    depends_on:
      - swag
  swag:
    container_name: swag
    restart: unless-stopped
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=example.com
      - VALIDATION=dns
      - DNSPLUGIN=bunny
    volumes:
      - $PWD/config:/config
      - $PWD/site/:/var/www/html
      - php_socket:/run/php
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

volumes:
  php_socket:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
